#ifndef CURRENTSCHEMA_H_
#define CURRENTSCHEMA_H_

#include "src/db/schema/Schema.h"

class Interface;

/**
 * The current schema (the implementation is autogenerated)
 */
class CurrentSchema: public Schema
{
	public:
		CurrentSchema (Interface &interface);
		virtual ~CurrentSchema ();

		// Default parameters, but to implement Schema, we need to declare the
		// methods without parameters
		virtual void up () { up (OperationMonitorInterface::null); }
		virtual void down () { down (OperationMonitorInterface::null); }

		virtual void up (OperationMonitorInterface monitor);
		virtual void down (OperationMonitorInterface monitor);

		virtual QList<quint64> getVersions ();
};

#endif
