#!/bin/sh

# Script for /etc/init.d/startkladde which allows to start the X server and the
# startkladde program automatically. This requires more setup, see readme.txt.

case "$1" in
  start)
	echo "Starte Startkladde"
	su - startkladde ~startkladde/startkladde-up &
	;;
  stop)
	echo "Beende Startkladde"
	su - startkladde ~startkladde/startkladde-down
	;;
  restart|force-reload)
	echo "Start Startkladdensystem neu"
	$0 stop
	$0 start
	;;
  reload)
	echo "Starte Startkladde neu"
	killall startkladde
	;;
  *)
	N=$0
	echo "Usage: $N {start|stop|reload|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

