default: pdf

pdf: startkladde_bedienungsanleitung.tex
	pdflatex startkladde_bedienungsanleitung.tex

.PHONY: clean
clean:
	-rm startkladde_bedienungsanleitung.aux
	-rm startkladde_bedienungsanleitung.log
	-rm startkladde_bedienungsanleitung.out
	-rm startkladde_bedienungsanleitung.toc
	-rm startkladde_bedienungsanleitung.pdf

